<?php
/**
 * Created by PhpStorm.
 * User: leona
 * Date: 06/06/2018
 * Time: 21:26
 */

class GraduacaoQuery extends Query
{
    /**
     * Informe as colunas conforme declarado na tabela
     */
    CONST COLUNAS = array(
        'id',
        'sequencia',
        'descricao'
    );

    /**
     * Informe o nome da tabela
     */
    CONST TABELA = "graduacao";

    /**
     * Informe o nome da classe do objeto
     */
    CONST CLASSE = "Graduacao";

    /**
     * @param array $filtros Pode ser passado neste parâmetros valoes como: array("id = 1", "nome like '%Arquelau%'")
     * @param array $ordens Pode ser passado neste parâmetros valoes como: array("ordem asc", "nome desc")
     *
     * @return string
     */
    public static function sqlSimples($filtros = array(), $ordens = array())
    {
        /**
         * self indica que você quer utilizar a constante de fora deste método
         */
        return parent::sqlSimples(self::TABELA, self::COLUNAS, $filtros, $ordens); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $sql Este parâmetro é para você informar o select da sua consulta, pode ser utilizado o método sqlSimples() para gerar.
     *                  Caso houver a necessidade de fazer o select na mão, certifiquesse de passar todas as colunas conforme cadastrado
     *                  na constante COLUNAS.
     * @param bool $returnOne Este parâmetro indica ser você quer retornar um array de objetos populado com os registros da consulta ou se
     *                        deseja retornar somente o objeto do primeiro registro da consulta.
     *
     * @return array|mixed
     */
    public static function consultar($sql = null, $returnOne = false)
    {
        return parent::consultar(self::CLASSE, self::TABELA, self::COLUNAS, $sql, $returnOne); // TODO: Change the autogenerated stub
    }
}