<?php
/**
 * Created by PhpStorm.
 * User: leona
 * Date: 06/06/2018
 * Time: 21:26
 */

class MenuQuery extends Query
{
    CONST COLUNAS = array(
        'id',
        'descricao',
        'link',
        'icone',
        'ordem',
        'level',
        'parent'
    );

    CONST TABELA = "menu";
    CONST CLASSE = "Menu";

    public static function sqlSimples($filtros = array(), $ordens = array())
    {
        return parent::sqlSimples(self::TABELA, self::COLUNAS, $filtros, $ordens); // TODO: Change the autogenerated stub
    }

    public static function consultar($sql = null, $returnOne = false)
    {
        return parent::consultar(self::CLASSE, self::TABELA, self::COLUNAS, $sql, $returnOne); // TODO: Change the autogenerated stub
    }

    public static function montarMenu($level = 1, $parent = 1) {
        $html = '';

        $filtro = array(
            "level = $level",
            "parent = $parent"
        );

        $ordem = array(
            "ordem ASC"
        );

        $sql = self::sqlSimples($filtro, $ordem);

        foreach (MenuQuery::consultar($sql) as $objMenu) /** @var $objMenu Menu */ {

            $html .= sprintf(' <li class="nav-item %s" data-toggle="tooltip" data-placement="right" title="%s"> ', (strpos($objMenu->getLink(), MODULO) !== false ? 'active' : ''), $objMenu->getDescricao());
            $html .= sprintf(' <a class="nav-link" href="%s"> ', get_url_admin() . $objMenu->getLink());

            if (!is_null($objMenu->getIcone())) {
                $html .= sprintf(' <i class="%s"></i>', $objMenu->getIcone());
            }

            $html .= sprintf('<span class="nav-link-text">%s</span>', $objMenu->getDescricao());

            $html .= ' </a> ';
            $html .= ' </li> ';
        }

        $html .= "<li class='divider'></li>";

        $html .= sprintf(' <li class="nav-item %s" data-toggle="tooltip" data-placement="right" title="%s"> ', (strpos('menu', MODULO) !== false ? 'active' : ''), "Menu");
        $html .= sprintf(' <a class="nav-link" href="%s/menu/list.php"> ', get_url_admin());
        $html .= ' <i class="fa fa fa-sitemap"></i> ';
        $html .= '<span class="nav-link-text">Menu</span>';
        $html .= ' </a> </li> ';

        return $html;
    }
}